computer_science = input ("what is your computer_science grade ")
math = input ("what your math grade")
ESL = input ("what your esl grade")
science = input ("what you grade in science")
humanities = input ("what your grade in your humanities")
